<#
  Assembles the static web build in web\ so it can be served by GitHub Pages.

  The renderer is copied from app\renderer (single source of truth) with the pdf.js
  paths pointed at .js copies, since GitHub Pages does not always serve .mjs with a
  JavaScript MIME type. web\index.html, web\web-api.js and web\engine.js are the
  hand-written browser parts and are left alone.

  Usage:  powershell -ExecutionPolicy Bypass -File make-web.ps1
  Then publish the contents of web\ (e.g. push it to a gh-pages branch, or deploy it
  with a Pages workflow).
#>
[CmdletBinding()]
param([string]$OutDir = 'web')

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Definition
$web = Join-Path $root $OutDir
$renderer = Join-Path $root 'app\renderer'

function Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Fail($msg) { Write-Host "make-web failed: $msg" -ForegroundColor Red; exit 1 }

if (-not (Test-Path -LiteralPath $renderer)) { Fail "missing $renderer" }
New-Item -ItemType Directory -Force -Path (Join-Path $web 'vendor') | Out-Null

Step 'copying the renderer'
$appSource = Get-Content -LiteralPath (Join-Path $renderer 'app.js') -Raw
$appOut = $appSource.
  Replace('./vendor/pdf.min.mjs', './vendor/pdf.min.js').
  Replace('./vendor/pdf.worker.min.mjs', './vendor/pdf.worker.min.js')
$header = "// Generated by make-web.ps1 from app/renderer/app.js - edit that file, then re-run the script.`r`n"
Set-Content -LiteralPath (Join-Path $web 'app.js') -Value ($header + $appOut) -Encoding UTF8
Copy-Item -LiteralPath (Join-Path $renderer 'style.css') -Destination (Join-Path $web 'style.css') -Force

Step 'copying pdf.js'
Copy-Item -LiteralPath (Join-Path $renderer 'vendor\pdf.min.mjs') -Destination (Join-Path $web 'vendor\pdf.min.js') -Force
Copy-Item -LiteralPath (Join-Path $renderer 'vendor\pdf.worker.min.mjs') -Destination (Join-Path $web 'vendor\pdf.worker.min.js') -Force

Step 'copying the icon'
$icon = Join-Path $root 'app\icon.png'
if (Test-Path -LiteralPath $icon) { Copy-Item -LiteralPath $icon -Destination (Join-Path $web 'icon.png') -Force }

$size = (Get-ChildItem -LiteralPath $web -Recurse -File | Measure-Object -Property Length -Sum).Sum
Write-Host ''
Write-Host ("web build ready: {0} ({1:N1} MB of {2} files)" -f $web, ($size / 1MB), (Get-ChildItem -LiteralPath $web -Recurse -File).Count) -ForegroundColor Green
Write-Host 'publish the contents of that folder with GitHub Pages' -ForegroundColor DarkGray
